### ISSUE TITLE
Configuration of the sick through this API

### ISSUE THREAD

**Issue by ibrahimalnasser** [SICKAG/sick_safetyscanners_base#10]
Hello Dears, a question here regarding the API
could we Configure the sick sensor through this API or other APIs?
Thanks in advance

**Comment by lenpuc** [comment]
Hi, what exactly do you want to configure? The possible configurations of this cpp driver can be found here: https://github.com/SICKAG/sick_safetyscanners_base#parameters-of-communication-settings
However, this does not include any safety configurations, they have to be done via the SICK Software
