### ISSUE TITLE
Python Port Please

### ISSUE THREAD

**Issue by gabriel-wainmann** [SICKAG/sick_safetyscanners_base#12]
Would you be so kind as to make a Python wrapper for this ?

Thanks!

**Comment by lenpuc** [comment]
Hi,
this is currently not planned. 

If it is a possibility for you, you could use the ROS1 or ROS2 versions of this library and can subscribe to the relevant topics in your python nodes. However, this is most likely only a solution if you are already using ROS.

**Comment by gabriel-wainmann** [comment]
Would it be possible to get the raw data structure so I can write my own
code?

**Comment by lenpuc** [comment]
What do you mean by datastructure? The Protocol is available under: https://cdn.sick.com/media/docs/1/01/701/Technical_information_Data_output_via_UDP_and_TCP_IP_en_IM0083701.PDF

This driver here implements all the protocol outputs in C++

**Comment by gabriel-wainmann** [comment]
Thank you
