### ISSUE TITLE
Using only the Cola2-functionalitiy

### ISSUE THREAD

**Issue by LukasStu** [SICKAG/sick_safetyscanners_base#17]
Hi,

thanks for this great SICK MS3 driver. I want to use it to request some meta data without having to configure a UDP connection.
Requesting meta data works great with the `SyncSickSafteyScanner` class when setting `comm_settings.host_udp_port = 0`. However this causes a warning in the SICK Saftey Designer:

![image](https://user-images.githubusercontent.com/72215368/198197366-f57230c0-9a9f-4eef-950a-ac6eae01ebe9.png)

Is there a way/ a constructor that doesn't change the upd port?

Thx
Lukas

**Comment by lenpuc** [comment]
Hi, 

currently the driver always sets a UDP port for the output.
You probably could achieve the desired output by setting the `comm_settings.host_udp_port` to your desired port (same as in the safety designer). Otherwise you would need to implement the functionality.

**Comment by lenpuc** [comment]
Closing this, since no further action seems to be needed
