### ISSUE TITLE
Please update this repo to stay in sync with sick_safetyscanners

### ISSUE THREAD

**Issue by mlederhi** [SICKAG/sick_safetyscanners_base#24]
or better remove this repo altogether and provide a CMake switch in repository sick_safetyscanners to build a C++ library independent from ROS.

**Comment by lenpuc** [comment]
Hi, which feature are you missing? And yes, it would be better if it was one repo. However, the ROS driver was the first development, and it did branch into an independent driver with additional features for async and sync data processing. This base driver is underlying the ROS2 driver. So, from my side, I will integrate features as needed however the ROS1 driver will not be adapted with a standalone CPP option

**Comment by mlederhi** [comment]
A colleague of mine used the ROS1 driver version some time ago and commented out the ROS stuff so we could use the library in you C++ application. From the maintenance point of view it would have been nice, that we don't have to do this again with new releases of the library. I just thought, that this repo was left behind the ROS1 repo - but since it is based on the ROS2 version, you can probably close this issue.

**Comment by lenpuc** [comment]
Yes, it should not be left behind, and once ROS1 has its end of life this and the ROS2 driver will be the main components, and if something is missing, please just let me know.
