### ISSUE TITLE
'Synchronous Client' example in README.md appears to be broken

### ISSUE THREAD

**Issue by scotthea-amazon** [SICKAG/sick_safetyscanners_base#5]
Hello,

I have tried building the 'Synchronous Client' example from README.md. I ran into a couple of minor errors that I was able to address, but the following line fails to compile because the constructor has been deleted:
`auto safety_scanner = sick::SyncSickSafetyScanner(sensor_ip, tcp_port, comm_settings);`
Can someone explain how the 'Synchronous Client' case is supposed to work with the constructor deleted?

**Comment by lenpuc** [comment]
Hi, thanks for bringing this to my attention. Yes the copy constructor was deleted on purpose. Possible ways to create an instance would be (with the first being the preferred way):
```
auto safety_scanner = std::make_unique<sick::SyncSickSafetyScanner>(sensor_ip, tcp_port, comm_settings);
```
```
sick::SyncSickSafetyScanner safety_scanner(sensor_ip, tcp_port, comm_settings);
```

I'll adjust the readme for the examples.

**Comment by lenpuc** [comment]
Readme is updated

**Comment by scotthea-amazon** [comment]
Thank you for the quick update! It was very helpful.
