### ISSUE TITLE
Reading "Ethernet Packet - SICK output" bytes

### ISSUE THREAD

**Issue by scotthea-amazon** [SICKAG/sick_safetyscanners_base#6]
Hello,

I am trying to read the "Ethernet Packet - SICK output" bytes from a SICK CPU (see image below).  Is there a way to read those bytes using the API provided by this project? If not, can someone point me to a description of the commands that would be needed to read them?

![SICK_output_bytes](https://user-images.githubusercontent.com/7906129/108292231-8a7d8d00-7148-11eb-9438-a484eb4c4465.png)

**Comment by lenpuc** [comment]
Hi, I am not entirely sure where this data would bet. If the data you are looking for ist in the UDP Protocoll oder in the Cola2 variables they are readable. Have a look here: https://cdn.sick.com/media/docs/1/01/701/Technical_information_microScan3_outdoorScan3_en_IM0083701.PDF

Possibly your application is setting the output paths? If so the data is in the UDP protocol in the application outputs. You can receive them by calling the receive function of the synchronous API. The data package then contains the application outputs.

However, if its no where in the manual, it might be a safety related output which is not given by the protocol. Then this driver will not pick it up. Hope that helps.

**Comment by scotthea-amazon** [comment]
Thank you for the quick and helpful response!

If these values are in the ApplicationOutputs, would you expect them to be found in the monitoring case vector?

**Comment by lenpuc** [comment]
Might be possible. I am not entirely sure how the side of these applications gives the output to cola2 or the UDP protocol.
But yes this would be the first place I would check. But I can not give you a definite answer on this. Maybe the support of SICK can give you more feedback on this.

**Comment by lenpuc** [comment]
Closing this. If you got more answers please post them here.
